spring:
  application:
    name: happy_doggies
  datasource:
    url: jdbc:mysql://localhost:3306/happy_doggies_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop